apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: actors.iiot.mc-b.ch
spec:
  group: iiot.mc-b.ch
  scope: Cluster  
  names:
    plural: actors
    singular: actor
    kind: Actor
    shortNames:
      - act
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                state:
                  type: string
                topic:  
                  type: string                    
