apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devices.iiot.mc-b.ch
spec:
  group: iiot.mc-b.ch
  scope: Cluster  
  names:
    plural: devices
    singular: device
    kind: Device
    shortNames:
      - dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                type:  
                  type: string
                topic:  
                  type: string                  
                sensors:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      sensorRef:
                        type: string
                actors:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      actorRef:
                        type: string

