apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sensors.iiot.mc-b.ch
spec:
  group: iiot.mc-b.ch
  scope: Cluster  
  names:
    plural: sensors
    singular: sensor
    kind: Sensor
    shortNames:
      - sen
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                name:
                  type: string
                type:
                  type: string
                topic:  
                  type: string                       
                values:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      unit:
                        type: string
                      value:
                        type: string
                                           