apiVersion: iiot.mc-b.ch/v1alpha1
kind: Device
metadata:
  name: m5stack-core
spec:
  type: M5Stack Core
  topic: m5stackcore
  sensors:
    - name: enviii-sensor
      sensorRef: enviii
    - name: rfid-sensor
      sensorRef: rfid
  actors:
    - name: servo-actor
      actorRef: servo

