apiVersion: v1
kind: ServiceAccount
metadata:
  name: mqttservice-acc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mqttservice-crd
rules:
- apiGroups: ["iiot.mc-b.ch"]
  resources: ["mqttdevices"]
  verbs: ["get", "watch", "list", "patch", "update"]
- apiGroups: ["iiot.mc-b.ch"]
  resources: ["devices"]  
  verbs: ["get", "watch", "list", "patch", "update"]
- apiGroups: ["iiot.mc-b.ch"]
  resources: ["sensors"]  
  verbs: ["get", "watch", "list", "patch", "update"]
- apiGroups: ["iiot.mc-b.ch"]
  resources: ["actors"]  
  verbs: ["get", "watch", "list", "patch", "update"]    
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mqttservice-crd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mqttservice-crd
subjects:
  - kind: ServiceAccount
    name: mqttservice-acc
    namespace: default
